# Generated by Django 3.1.11 on 2021-05-23 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210523_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Register User', 'verbose_name_plural': 'Register Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, help_text='The contact number of the customer.', max_length=50, null=True, verbose_name='Contact number'),
        ),
        migrations.AddField(
            model_name='user',
            name='country_of_residence',
            field=models.CharField(blank=True, help_text='The country residence of the customer. KYC verification will be applied to this country and customer must provide proof of such residence as relevant in the country of jurisdiction.', max_length=250, null=True, verbose_name='Country of Residence'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_address',
            field=models.CharField(blank=True, help_text='The currently living address of the customer.', max_length=250, null=True, verbose_name='Current address'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='The date of birth of the customer.', null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_currency_id',
            field=models.CharField(blank=True, default='EUR', help_text='The default currency of the borrower. Currency will be sent against borrowers country of residence.', max_length=3, null=True, verbose_name='Default Currency ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='The first nammes of the customer.', max_length=50, null=True, verbose_name='First names'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, help_text='The Job title of the customer. ', max_length=250, null=True, verbose_name='Job title'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_complete',
            field=models.BooleanField(default=False, help_text='Flag to determine if a cutomer have completed KYC verification', verbose_name='KYC complete'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_complete_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when customer completed KYC verifiction process.', null=True, verbose_name='KYC complete date'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(blank=True, choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('action_required', 'Action_required'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected/Refused')], default='Unverified', help_text='The .', max_length=15, null=True, verbose_name='KYC status'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_submitted',
            field=models.BooleanField(blank=True, help_text='Flag to determine if customer has submitted a KYC verification.', null=True, verbose_name='KYC submitted'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='The last nammes of the customer.', max_length=50, null=True, verbose_name='Last names'),
        ),
        migrations.AddField(
            model_name='user',
            name='on_boarding_complete',
            field=models.BooleanField(blank=True, help_text='Flag to determine if customer has completed onboarding.', null=True, verbose_name='Completed Onboarding'),
        ),
        migrations.AddField(
            model_name='user',
            name='on_boarding_complete_date',
            field=models.DateField(blank=True, help_text='Timestamp when customer completed onboarding process.', null=True, verbose_name='Onboarding Complete date'),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_address',
            field=models.CharField(blank=True, help_text='The current permanent address of the customer.', max_length=250, null=True, verbose_name='Permanent address'),
        ),
        migrations.AddField(
            model_name='user',
            name='place_of_birth',
            field=models.CharField(blank=True, help_text='The place fo birth of the customer. This must match the place of birth as indicated in the cusomters photo Identification.', max_length=250, null=True, verbose_name='Place of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='registered_ip_address',
            field=models.GenericIPAddressField(blank=True, editable=False, help_text='The Ip address recorded at the time if registeration.', null=True, verbose_name='Registered Ip Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_security_number',
            field=models.CharField(blank=True, help_text='The social security number of the customer. This helps to determine the credit score and also validates the identity of the customer. ', max_length=50, null=True, verbose_name='Social security number'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when customer is been verified.', null=True, verbose_name='Verification date'),
        ),
    ]
