# Generated by Django 3.1.11 on 2021-05-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210523_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='The email address of the customer.', max_length=150, null=True, unique=True, verbose_name='Email Address'),
        ),
    ]
