# Generated by Django 3.1.11 on 2021-06-01 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0005_auto_20210524_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_of_residence',
            field=models.ForeignKey(blank=True, help_text='The country residence of the customer. KYC verification will be applied to this country and customer must provide proof of such residence as relevant in the country of jurisdiction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.country', verbose_name='Country of Residence'),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, help_text='Address line 1 of the user', max_length=50, null=True, verbose_name='Address line 1')),
                ('address_line_2', models.CharField(blank=True, help_text='Address line 2 of the user', max_length=50, null=True, verbose_name='Address line 2')),
                ('state', models.CharField(blank=True, help_text='State or Region of the user', max_length=50, null=True, verbose_name='State or Region')),
                ('zip_post_code', models.CharField(blank=True, help_text='Zip post code of the user address', max_length=50, null=True, verbose_name='Zip Post Code')),
                ('country', models.ForeignKey(blank=True, help_text='Country of the user', null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.country', verbose_name='Country')),
                ('user', models.ForeignKey(help_text='The user for whom address belongs to', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Address',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='current_address',
            field=models.ForeignKey(blank=True, help_text='The currently living address of the customer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.useraddress', verbose_name='Current address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permanent_address',
            field=models.ForeignKey(blank=True, help_text='The current permanent address of the customer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.useraddress', verbose_name='Permanent address'),
        ),
    ]
