# Generated by Django 3.1.11 on 2021-06-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210601_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='type',
            field=models.CharField(choices=[('current', 'Current Address'), ('permanent', 'Permanent Address')], default='current', help_text='The type of address.', max_length=9, verbose_name='Address Type'),
        ),
    ]
