# Generated by Django 3.1.11 on 2021-06-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_useraddress_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('borrower', 'Borrower'), ('investor', 'Investor')], help_text='Account type', max_length=8, verbose_name='Name of User'),
        ),
    ]
