# Generated by Django 3.1.11 on 2021-06-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('borrower', 'Borrower'), ('investor', 'Investor')], default='borrower', help_text='Account type', max_length=8, null=True, verbose_name='Name of User'),
        ),
    ]
