# Generated by Django 3.1.11 on 2021-06-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210601_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('borrower', 'Borrower'), ('investor', 'Investor')], default='borrower', help_text='Account type', max_length=8, null=True, verbose_name='Account Type'),
        ),
    ]
